[package]
name = "stem_cli"
description = "The `stemma` command-line interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "stemma"
path = "src/main.rs"

[dependencies]
stem_core.workspace = true
stem_genome.workspace = true
stem_io.workspace = true
stem_phonology.workspace = true
anyhow.workspace = true
clap.workspace = true

[lints]
workspace = true
