[package]
name = "stem_cli"
description = "The `stemma` command-line interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "stemma"
path = "src/main.rs"

[dependencies]
stem_core.workspace = true
stem_genome.workspace = true
stem_io.workspace = true
stem_phonology.workspace = true
anyhow.workspace = true
clap.workspace = true
stem_lexicon.workspace = true
stem_export.workspace = true
stem_soundchange.workspace = true
stem_syntax.workspace = true
stem_script.workspace = true
stem_assist.workspace = true
stem_embodiment.workspace = true

[dev-dependencies]
sha2.workspace = true
ron.workspace = true
serde_json.workspace = true

[lints]
workspace = true
