//! The portfolio artefact — "Growing a Language Family in 90 Seconds"
//! (`DESIGN.md` §21).
//!
//! A **pure projection**: [`write_family_demo`] renders an already-built family
//! (`docs/adr/0006` — building lives in `stem_genome::grow_family`, rendering
//! here). No `evolve`, no RNG, no clock, no map, no sort — the bytes are a
//! function of the inputs alone, so the document reproduces byte-for-byte (§9.4).
//! [`write_asterian_demo`] bakes the one canonical recipe (branches, meanings,
//! the five etymologies, the prose) so the CLI, the golden test, and the M11 UI
//! all emit the identical document.

use std::fmt::Write;

use stem_core::{Result, StemmaError, ValidationReport};
use stem_genome::{BranchSpec, CognateTable, LanguageGenome, LineageGraph, grow_family};
use stem_soundchange::{RuleSet, render_derivation};

use crate::cognate_table::write_cognate_table_markdown;
use crate::markdown::{escape, fmt_err};

/// The editorial content of the family document — the prose the model cannot
/// supply. Every *form*, rule history, and table cell comes from the graph and
/// table, never from here, so the facts cannot drift from the engine.
#[derive(Debug, Clone)]
pub struct DemoDoc<'a> {
    /// The H1 title.
    pub title: &'a str,
    /// The opening pitch paragraph.
    pub pitch: &'a str,
    /// One blurb per daughter, in graph node order (parallel to the daughters,
    /// i.e. `graph.nodes()[1..]`).
    pub branch_blurbs: &'a [&'a str],
    /// A one-line reading of the table (e.g. "one etymon, three roads"), printed
    /// under it. Empty to omit — this is family-specific editorial, so it lives
    /// here rather than in the general renderer.
    pub table_reading: &'a str,
    /// The etymologies to spell out in full, in document order.
    pub traces: &'a [TracePick<'a>],
    /// The "what this demonstrates / road ahead" closer.
    pub closer: &'a str,
}

/// One etymology to trace: a daughter language id and the meaning to resolve
/// there via `Lexicon::by_meaning` — the same resolver `cognates`/`trace-word`
/// use, so the demo cannot disagree with them about what a meaning names.
#[derive(Debug, Clone, Copy)]
pub struct TracePick<'a> {
    pub language: &'a str,
    pub meaning: &'a str,
}

/// The dateless colophon — a determinism statement, no wall-clock time (§9.4).
const COLOPHON: &str = "*Generated by Stemma from a proto-language and an ordered rule set. \
Every form above is reproducible byte-for-byte from the same inputs — no wall-clock \
time, no unseeded randomness.*";

/// Renders the §21 family document into `out` from an **already-built** model.
///
/// A pure projection (`docs/adr/0006`): it reads the graph's node `applied_rules`
/// for the daughter histories, calls [`write_cognate_table_markdown`] for the
/// table, and [`render_derivation`] for each trace. The graph's first node is the
/// proto; the rest are daughters in node order, parallel to `doc.branch_blurbs`.
pub fn write_family_demo(
    out: &mut String,
    graph: &LineageGraph,
    table: &CognateTable,
    doc: &DemoDoc<'_>,
) -> Result<()> {
    let proto = graph
        .nodes()
        .first()
        .ok_or_else(|| StemmaError::not_found("proto language", "the family is empty"))?;

    // --- Title + pitch ---
    writeln!(out, "# {}", doc.title).map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(out, "{}", doc.pitch).map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;

    // --- The proto-language ---
    writeln!(out, "## The proto-language — {}", escape(&proto.name)).map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(
        out,
        "{} attested roots, the ancestor every modern form below descends from. \
         Stress is fixed on the first syllable — which is what makes \"final \
         *unstressed* vowel loss\" a real conditioned rule rather than \"drop the \
         last vowel\".",
        proto.lexicon.len()
    )
    .map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(out, "| Gloss | Form | IPA |").map_err(fmt_err)?;
    writeln!(out, "| --- | --- | --- |").map_err(fmt_err)?;
    for entry in proto.lexicon.iter() {
        let gloss = entry
            .display_gloss()
            .ok_or_else(|| StemmaError::not_found("gloss", &entry.id))?;
        writeln!(
            out,
            "| {} | {} | /{}/ |",
            escape(gloss),
            escape(&entry.written(&proto.phonemes)?),
            escape(&entry.ipa(&proto.phonemes)?),
        )
        .map_err(fmt_err)?;
    }
    writeln!(out).map_err(fmt_err)?;
    writeln!(
        out,
        "The full dictionary — every form with its cognate set — is one command away: \
         `stemma export-md <file>`."
    )
    .map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;

    // --- The daughters ---
    let daughters = &graph.nodes()[1..];
    if !daughters.is_empty() {
        writeln!(out, "## The daughters").map_err(fmt_err)?;
        writeln!(out).map_err(fmt_err)?;
        writeln!(
            out,
            "Each branched off and underwent its own ordered sound-change history \
             (dates are years since the proto-language):"
        )
        .map_err(fmt_err)?;
        writeln!(out).map_err(fmt_err)?;
        for (i, daughter) in daughters.iter().enumerate() {
            // The heading shows the edge delta from the proto (the rendered
            // ancestor), never the daughter's absolute depth — they coincide only
            // when the proto is a depth-0 root, which is not guaranteed in general.
            writeln!(
                out,
                "### {} — +{}y from {}",
                escape(&daughter.name),
                daughter.lineage_depth_years - proto.lineage_depth_years,
                escape(&proto.name),
            )
            .map_err(fmt_err)?;
            writeln!(out).map_err(fmt_err)?;
            if let Some(blurb) = doc.branch_blurbs.get(i) {
                writeln!(out, "{blurb}").map_err(fmt_err)?;
                writeln!(out).map_err(fmt_err)?;
            }
            // The rule history, rendered FROM the evolved genome (never hand-typed,
            // so it cannot silently drift from the fixtures actually applied).
            for rule in &daughter.applied_rules {
                writeln!(
                    out,
                    "- {} — at {}y",
                    escape(&rule.name),
                    rule.chronology_years
                )
                .map_err(fmt_err)?;
            }
            writeln!(out).map_err(fmt_err)?;
        }
    }

    // --- The cognate table ---
    writeln!(out, "## Comparative cognate table").map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(
        out,
        "Reflexes of each meaning across the family, joined by **shared ancestry** \
         (cognate set) rather than by meaning — so a reflex holds its row even if \
         its sense later drifts on one branch."
    )
    .map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    write_cognate_table_markdown(out, table)?;
    if !doc.table_reading.is_empty() {
        writeln!(out).map_err(fmt_err)?;
        writeln!(out, "{}", doc.table_reading).map_err(fmt_err)?;
    }
    writeln!(out).map_err(fmt_err)?;

    // --- The etymologies ---
    writeln!(out, "## {} etymologies", spell_out(doc.traces.len())).map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(
        out,
        "A strange-looking word is strange *for a reason*. Here is each one's full \
         derivation, rule by rule — including a rule that could have fired but did \
         not, so the trace explains a *skip* as well as a change."
    )
    .map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    for pick in doc.traces {
        let daughter = graph
            .get(&pick.language.into())
            .ok_or_else(|| StemmaError::not_found("language", pick.language))?;
        let matches = daughter.lexicon.by_meaning(pick.meaning);
        let entry = matches
            .first()
            .ok_or_else(|| StemmaError::not_found("meaning", pick.meaning))?;
        let proto_form = proto
            .lexicon
            .by_cognate_set(&entry.cognate_set)
            .ok_or_else(|| StemmaError::not_found("cognate set", &entry.cognate_set))?
            .written(&proto.phonemes)?;
        let modern = entry.written(&daughter.phonemes)?;

        writeln!(
            out,
            "### {} — {}: *{} → {}",
            escape(pick.meaning),
            escape(&daughter.name),
            escape(&proto_form),
            escape(&modern),
        )
        .map_err(fmt_err)?;
        writeln!(out).map_err(fmt_err)?;
        writeln!(out, "```text").map_err(fmt_err)?;
        // render_derivation returns a newline-terminated block; push it verbatim.
        out.push_str(&render_derivation(
            entry,
            &daughter.applied_rules,
            &daughter.phonemes,
        )?);
        writeln!(out, "```").map_err(fmt_err)?;
        writeln!(out).map_err(fmt_err)?;
    }

    // --- Closer + colophon ---
    writeln!(out, "## What this demonstrates").map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(out, "{}", doc.closer).map_err(fmt_err)?;
    writeln!(out).map_err(fmt_err)?;
    writeln!(out, "---").map_err(fmt_err)?;
    writeln!(out, "{COLOPHON}").map_err(fmt_err)?;

    Ok(())
}

/// Spells a small count as an English word (document prose reads "Five
/// etymologies", not "5 etymologies"). Falls back to digits past the range the
/// demo uses.
fn spell_out(n: usize) -> String {
    match n {
        0 => "No".to_owned(),
        1 => "One".to_owned(),
        2 => "Two".to_owned(),
        3 => "Three".to_owned(),
        4 => "Four".to_owned(),
        5 => "Five".to_owned(),
        6 => "Six".to_owned(),
        other => other.to_string(),
    }
}

/// The canonical portfolio artefact: grows the Asterian family, builds the table,
/// bakes the recipe (branches, years, table meanings, the five etymologies, the
/// prose) ONCE, and renders via [`write_family_demo`]. The CLI, the golden test,
/// and the M11 UI all call this, so the document's story lives in one place.
///
/// Returns the merged advisory report (warnings/notes only for the reference
/// family — the `target_matches_nothing` notes for the velar-chain rules whose
/// class is empty until an earlier rule mints into it).
pub fn write_asterian_demo(
    out: &mut String,
    proto: &LanguageGenome,
    coastal: &RuleSet,
    highland: &RuleSet,
    riverine: &RuleSet,
) -> Result<ValidationReport> {
    // Branch years equal each rule file's last `chronology_years` (absolute from
    // the root), keeping `lineage_depth_years` and the timeline agreed.
    let branches = [
        BranchSpec {
            id: "coastal",
            name: "Coastal Asterian",
            rules: coastal,
            years: 470,
        },
        BranchSpec {
            id: "highland",
            name: "Highland Asterian",
            rules: highland,
            years: 460,
        },
        BranchSpec {
            id: "riverine",
            name: "Riverine Asterian",
            rules: riverine,
            years: 420,
        },
    ];
    let (graph, reports) = grow_family(proto, &branches)?;

    let meanings: Vec<String> = ["water", "sun", "star", "stone", "king", "mother"]
        .iter()
        .map(|m| (*m).to_owned())
        .collect();
    let table = graph.cognate_table(&meanings)?;

    let doc = DemoDoc {
        title: "Growing a Language Family in 90 Seconds",
        pitch: "One proto-language, three daughters, and roughly five centuries of simulated \
                change. Every modern form below carries a complete, rule-derived causal history \
                — nothing here was chosen at random. The whole document is deterministic: the \
                same proto-language and the same three ordered rule files reproduce it \
                byte-for-byte.",
        branch_blurbs: &[
            // coastal
            "The innovator. Intervocalic voicing feeds lenition feeds loss, and final \
             unstressed vowels drop — so its velars hollow out entirely: *takala* becomes \
             *taal*.",
            // highland
            "Shares voicing and apocope with the coast, but assimilates nasals instead of \
             leniting, so its velars survive as stops: *takala* becomes *tagal*.",
            // riverine
            "The conservative branch. It never voiced and never lost a final vowel; a \
             velar-loss-then-coalescence chain of its own gives *takala* → *tala*, and it \
             keeps the vowels its sisters drop.",
        ],
        table_reading: "One etymon, `*takala`, takes three roads — `taal`, `tagal`, `tala`: \
                        the comparative method in a single row.",
        traces: &[
            TracePick {
                language: "coastal",
                meaning: "star",
            },
            TracePick {
                language: "riverine",
                meaning: "star",
            },
            TracePick {
                language: "highland",
                meaning: "stone",
            },
            TracePick {
                language: "coastal",
                meaning: "king",
            },
            TracePick {
                language: "riverine",
                meaning: "mother",
            },
        ],
        closer: "Every surface form was produced by an ordered rule, not chosen; each etymology \
                 replays from proto to modern, step by step, and even a rule that found no \
                 target is on the record. The table joins by cognate set — shared ancestry — so \
                 a reflex keeps its row no matter what its meaning later does. And the whole \
                 document is a pure function of one proto-language and three rule files: same \
                 inputs, identical bytes.\n\nStill ahead, and named honestly rather than faked: \
                 **meaning drift** (a reflex coming to mean something new on one branch while \
                 its sisters keep the old sense), **morphology and a grammar sketch**, a \
                 readable rule notation, and a visual explorer. For the full dictionary as \
                 Markdown or CLDF-shaped CSV, run `stemma export-md` or `stemma export-csv`.",
    };

    write_family_demo(out, &graph, &table, &doc)?;

    // Merge the daughters' advisory reports, each scoped by its language id.
    let mut report = ValidationReport::new();
    for (branch, daughter_report) in branches.iter().zip(reports) {
        report.absorb(branch.id, daughter_report);
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;
    use stem_core::{CognateSetId, PhonemeId, WordId};
    use stem_genome::{CognateColumn, CognateRow};
    use stem_lexicon::{Derivation, Lexicon, PartOfSpeech, WordEntry, WordSource};
    use stem_phonology::{FeatureBundle, Phoneme, PhonemeInventory, Root, SegmentKind, Syllable};

    /// A vowel /a/ and a consonant /t/, validly featured, so a hand-built genome
    /// validates and its forms render.
    fn inventory() -> PhonemeInventory {
        let bundle = |tokens: &[&str]| {
            FeatureBundle::try_from(tokens.iter().map(|s| (*s).to_owned()).collect::<Vec<_>>())
                .expect("valid bundle")
        };
        PhonemeInventory::from_phonemes([
            Phoneme::new("ph_t", "t", SegmentKind::Consonant).with_features(bundle(&[
                "-syllabic",
                "+consonantal",
                "-sonorant",
                "-approximant",
                "-continuant",
                "-nasal",
                "-lateral",
                "-trill",
                "-voice",
                "-labial",
                "+coronal",
                "-dorsal",
            ])),
            Phoneme::new("ph_a", "a", SegmentKind::Vowel).with_features(bundle(&[
                "+syllabic",
                "-consonantal",
                "+sonorant",
                "+approximant",
                "+continuant",
                "-nasal",
                "-lateral",
                "-trill",
                "+voice",
                "-labial",
                "-coronal",
                "+dorsal",
                "-high",
                "+low",
                "+back",
                "-round",
            ])),
        ])
    }

    fn word(id: &str, gloss: &str, set: &str, segs: &[&str]) -> WordEntry {
        WordEntry {
            id: WordId::new(id),
            concept: None,
            phonemic_form: Root {
                syllables: vec![Syllable {
                    pattern: "CV".to_owned(),
                    segments: segs.iter().map(|s| PhonemeId::new(*s)).collect(),
                    stress: None,
                }],
            },
            glosses: vec![gloss.to_owned()],
            part_of_speech: PartOfSpeech::Noun,
            cognate_set: CognateSetId::new(set),
            source: WordSource::Authored,
            trace: None,
            morphemes: Vec::new(),
        }
    }

    /// A hand-built family: proto "ta", daughter "taa" with a hand-authored
    /// (empty-step) derivation so `render_derivation` renders without any engine
    /// run. Because `write_family_demo` is a *pure* renderer, no `evolve` runs —
    /// so this canary is a true renderer-only tripwire: no fixture and no engine
    /// change can move its bytes.
    fn canary_graph() -> LineageGraph {
        let proto = LanguageGenome::proto("proto", "Proto")
            .with_phonemes(inventory())
            .with_lexicon(Lexicon::from_entries([word(
                "w_0001",
                "star",
                "cog_1",
                &["ph_t", "ph_a"],
            )]));

        let mut daughter = proto.clone();
        daughter.id = "daughter".into();
        daughter.name = "Daughter".to_owned();
        daughter.parent = Some("proto".into());
        daughter.lineage_depth_years = 100;
        // The daughter's word carries a derivation whose input is the proto-form
        // and whose steps are empty — a word that "evolved" but underwent no
        // change, which render_derivation still renders in full.
        let mut entry = word("w_0001", "star", "cog_1", &["ph_t", "ph_a"]);
        entry.trace = Some(Derivation {
            input: entry.phonemic_form.clone(),
            steps: Vec::new(),
        });
        daughter.lexicon = Lexicon::from_entries([entry]);

        LineageGraph::assemble(vec![proto, daughter])
    }

    fn canary_table(graph: &LineageGraph) -> CognateTable {
        let columns = graph
            .nodes()
            .iter()
            .map(|g| CognateColumn {
                id: g.id.clone(),
                name: g.name.clone(),
                is_root: g.parent.is_none(),
            })
            .collect();
        CognateTable {
            columns,
            reference: "proto".into(),
            rows: vec![CognateRow {
                meaning: "star".to_owned(),
                cognate_set: Some(CognateSetId::new("cog_1")),
                cells: vec![Some("ta".to_owned()), Some("ta".to_owned())],
            }],
            notes: Vec::new(),
        }
    }

    fn canary_doc() -> DemoDoc<'static> {
        DemoDoc {
            title: "A Family",
            pitch: "A tiny family.",
            branch_blurbs: &["The only daughter."],
            table_reading: "One row.",
            traces: &[TracePick {
                language: "daughter",
                meaning: "star",
            }],
            closer: "That is all.",
        }
    }

    #[test]
    fn the_family_demo_canary_matches_its_frozen_bytes() {
        let graph = canary_graph();
        let table = canary_table(&graph);
        let mut out = String::new();
        write_family_demo(&mut out, &graph, &table, &canary_doc()).unwrap();

        // Frozen bytes — a renderer-only tripwire. `write_family_demo` is a pure
        // projection over a hand-built graph (no engine runs; the daughter's
        // derivation is hand-authored), so no fixture and no `apply.rs` change can
        // move these bytes: a diff here means the demo renderer itself changed.
        // Inline, never a golden file (the M1 canary-vs-golden discipline).
        let expected = "# A Family\n\nA tiny family.\n\n## The proto-language — Proto\n\n1 attested roots, the ancestor every modern form below descends from. Stress is fixed on the first syllable — which is what makes \"final *unstressed* vowel loss\" a real conditioned rule rather than \"drop the last vowel\".\n\n| Gloss | Form | IPA |\n| --- | --- | --- |\n| star | ta | /ta/ |\n\nThe full dictionary — every form with its cognate set — is one command away: `stemma export-md <file>`.\n\n## The daughters\n\nEach branched off and underwent its own ordered sound-change history (dates are years since the proto-language):\n\n### Daughter — +100y from Proto\n\nThe only daughter.\n\n\n## Comparative cognate table\n\nReflexes of each meaning across the family, joined by **shared ancestry** (cognate set) rather than by meaning — so a reflex holds its row even if its sense later drifts on one branch.\n\n| Meaning | Proto | Daughter |\n| --- | --- | --- |\n| star | *ta | ta |\n\n*Proto-forms (marked \\*) are reconstructions.*\n\nOne row.\n\n## One etymologies\n\nA strange-looking word is strange *for a reason*. Here is each one's full derivation, rule by rule — including a rule that could have fired but did not, so the trace explains a *skip* as well as a change.\n\n### star — Daughter: *ta → ta\n\n```text\n*ta  \"star\"  cog_1\n\n  proto      ta            /ta/\n  │\n  modern     ta            /ta/\n```\n\n## What this demonstrates\n\nThat is all.\n\n---\n*Generated by Stemma from a proto-language and an ordered rule set. Every form above is reproducible byte-for-byte from the same inputs — no wall-clock time, no unseeded randomness.*\n";
        assert_eq!(out, expected, "the family-demo renderer drifted");
    }

    #[test]
    fn the_family_demo_is_a_pure_function_of_its_inputs() {
        let graph = canary_graph();
        let table = canary_table(&graph);
        let render = || {
            let mut out = String::new();
            write_family_demo(&mut out, &graph, &table, &canary_doc()).unwrap();
            out
        };
        assert_eq!(render(), render(), "same inputs, identical bytes");
    }
}
